/**
 * My Menuply four questions + connections eat-together conversion.
 * Settings and Share stay on /account, not on My Menuply. Allergies not on the hub.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

function read(rel) {
  return fs.readFileSync(path.join(root, rel), "utf8");
}

test("My Menuply is the diner's personal home", () => {
  const page = read("src/pages/consumer/MyMenuplyPage.jsx");
  const section = read("src/pages/consumer/myMenuply/EatingHubSection.jsx");
  const bits = read("src/pages/consumer/myMenuply/myMenuplyBits.jsx");
  const hero = read("src/pages/consumer/myMenuply/DinerIdentityHero.jsx");
  const eatingPage = read("src/pages/consumer/ConnectionsEatingPage.jsx");
  assert.match(page, /DinerIdentityHero/);
  assert.match(page, /EatingHubSection/);
  assert.match(section, /data-testid="eating"/);
  assert.doesNotMatch(page, /data-testid="eating-plans"/);
  assert.doesNotMatch(page, /data-testid="what-im-eating"/);
  assert.doesNotMatch(page, /data-testid="want-to-eat"/);
  assert.match(page, /data-testid="dining-crews"/);
  assert.match(page, /data-testid="my-events"/);
  assert.doesNotMatch(page, /title="My Eating Plans"/);
  assert.match(section, /eating-calendar/);
  assert.match(section, /DinerCalendarTrigger/);
  assert.match(section, /PostAfterActions/);
  assert.match(section, /Invite Me/);
  assert.match(section, /EatingPlanDayForm/);
  assert.match(page, /joinCandidates/);
  assert.match(page, /listPendingEatInvitePeople/);
  assert.match(section, /future-plans-summary/);
  assert.match(section, /Schedule a plan/);
  assert.match(section, /No plans scheduled/);
  assert.doesNotMatch(section, /^\s*Plans Scheduled\s*$/m);
  assert.match(page, /isScheduledEatingPlan/);
  assert.match(section, /FuturePlanRow/);
  assert.doesNotMatch(section, /empty="Nothing yet."/);
  assert.match(page, /My Crews/);
  assert.match(page, /My Events/);
  assert.match(page, /DiningCrewHubCard/);
  assert.match(page, /NamedShareCard/);
  assert.match(page, /CrewQuickCompose/);
  assert.match(page, /description: purpose/);
  assert.match(page, /Invite people to join/);
  assert.match(page, /inviteToDiningCrew/);
  assert.match(page, /inviteToVenueEventGroup/);
  assert.match(page, /ShareModal/);
  assert.match(page, /buildDiningCrewInviteShareData/);
  assert.match(page, /buildMenuplyPathShareData/);
  assert.match(page, /visibility: "public"/);
  assert.doesNotMatch(page, /navigator\.share/);
  assert.match(section, /EatingCompose/);
  assert.match(page, /createWhatIAteToday/);
  assert.match(page, /mapDiaryEntriesForHub/);
  assert.match(section, /onSkip/);
  assert.match(page, /createWhatWeDoingSession/);
  assert.match(page, /createDiningCrew/);
  assert.match(page, /createWantToEat/);
  const after = read("src/pages/consumer/myMenuply/PostAfterActions.jsx");
  assert.match(after, /People can join/);
  assert.match(after, /How many can join/);
  assert.match(after, /searchReportPlaces/);
  assert.match(after, /Tag a dish/);
  assert.match(after, /Recipe/);
  assert.match(after, /Homemade/);
  assert.match(after, /Skip for now/);
  assert.match(after, /optional/);
  assert.match(after, /WHAT_I_ATE_MEAL_PERIODS/);
  assert.match(after, /updateWantToEat/);
  assert.match(after, /suggestWhatIAteTodayMenuItems/);
  assert.match(after, /want-link-menu-item/);
  assert.match(after, /updateWhatWeDoingSession/);
  assert.match(after, /updateWhatIAteToday/);
  assert.match(bits, /EatingPlanCard/);
  assert.match(bits, /Add details/);
  assert.match(bits, /View dish/);
  assert.match(bits, /restaurant_name/);
  assert.match(bits, /Restaurant/);
  assert.match(bits, /Add photo or video/);
  assert.match(bits, /MenuplyMediaPicker/);
  assert.match(bits, /Request to join/);
  assert.match(bits, /isScheduledEatingPlan/);
  const form = read("src/pages/consumer/myMenuply/EatingPlanDayForm.jsx");
  assert.match(form, /EatingPlaceFields/);
  assert.match(form, /restaurantLabel/);
  assert.match(form, /homemade/);
  assert.match(form, /JoinMeAudiencePicker/);
  assert.match(form, /joinAllowedUserIds/);
  const placeFields = read("src/pages/consumer/myMenuply/EatingPlaceFields.jsx");
  assert.match(placeFields, /asRestaurantPlace/);
  assert.match(placeFields, /eating-place-homemade/);
  const picker = read("src/pages/consumer/myMenuply/JoinMeAudiencePicker.jsx");
  assert.match(picker, /Anyone Connect/);
  assert.match(picker, /Select specific/);
  assert.match(picker, /Pending Invite/);
  const candidates = read("src/pages/consumer/myMenuply/joinMeCandidates.js");
  assert.match(candidates, /pendingInvites/);
  assert.match(candidates, /"invite"/);
  assert.match(bits, /NamedShareCard/);
  assert.match(bits, /cardTitleLink/);
  assert.match(bits, /DiningCrewHubCard/);
  assert.match(bits, /crew-purpose/);
  assert.match(bits, /crewPurposeText/);
  assert.match(bits, /Invite people to join/);
  const api = read("src/lib/consumerApi.js");
  assert.match(api, /joinWhatWeDoingSession/);
  assert.match(api, /listPendingEatInvitePeople/);
  assert.match(api, /\/api\/consumer\/want-to-eat/);
  assert.match(hero, /About Me/);
  assert.match(read("src/pages/consumer/myMenuply/MyMenuplyPresentationRails.jsx"), /Connections/);
  assert.match(hero, /viewerUserId/);
  assert.match(page, /MyMenuplyPresentationRails/);
  assert.match(page, /buildTopHighlights/);
  assert.match(read("src/pages/consumer/myMenuply/MyMenuplyPresentationRails.jsx"), /connections-avatar-strip/);
  assert.match(read("src/pages/consumer/myMenuply/MyMenuplyPresentationRails.jsx"), /\/my-menuply\/connections-eating/);
  assert.match(eatingPage, /StickyPageHeader title="My Connections"/);
  const eatingCompose = read("src/pages/consumer/myMenuply/EatingCompose.jsx");
  assert.match(eatingCompose, /MenuplyMediaPicker/);
  assert.match(eatingCompose, /eating-compose-media/);
  assert.match(section, /WantToEatList/);
  const calendar = read("src/pages/consumer/myMenuply/DinerCalendarSheet.jsx");
  assert.match(calendar, /diner-calendar-open/);
  assert.match(calendar, /calendar-event/);
  assert.match(calendar, /EatingHubCalendar/);
  assert.ok(page.indexOf("<DinerIdentityHero") < page.indexOf("<MyMenuplyPresentationRails"));
  assert.ok(page.indexOf("<MyMenuplyPresentationRails") < page.indexOf("<EatingHubSection"));
  assert.ok(page.indexOf("<EatingHubSection") < page.indexOf('data-testid="dining-crews"'));
  assert.doesNotMatch(page, /What My Connections Are Eating/);
  assert.doesNotMatch(page, /What My Connections Are Planning/);
  assert.doesNotMatch(page, /Where I Eat/);
  assert.doesNotMatch(page, /Dining Crews/);
  assert.doesNotMatch(page, /actionLabel/);
  assert.doesNotMatch(page, /See all/);
  assert.doesNotMatch(page, /What's happening/);
  assert.doesNotMatch(page, /public-activity/);
  assert.doesNotMatch(page, /\/waiter#activity/);
  assert.doesNotMatch(page, /allergen/i);
  assert.doesNotMatch(page, /dietary_preferences/);
  assert.doesNotMatch(bits, /actionLabel/);
  assert.doesNotMatch(hero, /Share My Menuply/);
  assert.doesNotMatch(hero, /Settings/);
  assert.doesNotMatch(hero, /\/account\/diner-qr/);
});

test("Connections eating cards link to menu items and Join Me / Invite to Eat", () => {
  const bits = read("src/pages/consumer/myMenuply/myMenuplyBits.jsx");
  const social = read("src/pages/consumer/myMenuply/EatingSocialActions.jsx");
  assert.match(bits, /View Menu Item/);
  assert.match(bits, /Join Me/);
  assert.match(bits, /EatingSocialActions/);
  assert.match(bits, /\/menu-items\//);
  assert.doesNotMatch(bits, /follower/);
  assert.match(social, /LikeMenuItemButton/);
  assert.match(social, /ShareButton/);
  assert.match(social, /InviteToEatButton/);
  assert.match(social, /#food-comments/);
  assert.match(social, /buildDishShareData/);
  assert.doesNotMatch(bits, /🌭/);
  assert.match(bits, /Add photo or video/);
});

test("Activity is broader happening and does not replace connections eating", () => {
  const activity = read("src/components/WaiterPublicActivity.jsx");
  const redirect = read("src/pages/ActivityPage.jsx");
  const waiter = read("src/pages/FoodInterestsPage.jsx");
  assert.match(activity, /not what your connections are eating/i);
  assert.match(activity, /\/my-menuply/);
  assert.match(activity, /What People Are Eating/);
  assert.doesNotMatch(activity, /What My Connections Are Eating/);
  assert.match(redirect, /\/waiter#activity/);
  assert.match(waiter, /WaiterPublicActivity/);
});

test("Settings dashboard stays at /account and points to My Menuply", () => {
  const profile = read("src/pages/consumer/ConsumerProfile.jsx");
  const social = read("src/pages/consumer/accountDashboard/SocialCrewTab.jsx");
  assert.match(profile, /Settings/);
  assert.match(social, /\/my-menuply/);
  assert.match(social, /Open My Menuply/);
});

test("Consumer API calls connections eating/planning aggregators", () => {
  const api = read("src/lib/consumerApi.js");
  assert.match(api, /\/api\/consumer\/connections\/eating/);
  assert.match(api, /\/api\/consumer\/connections\/planning/);
});
