const FONT = "Inter, Arial, sans-serif";

export const accountStyles = {
  page: {
    minHeight: "100vh",
    background: "var(--gb-color-page, #ffffff)",
    fontFamily: FONT,
    padding: "0 0 calc(var(--bottom-nav-h, 72px) + 16px)",
  },
  pageInner: {
    maxWidth: 680,
    margin: "0 auto",
    padding: "16px 16px 32px",
    boxSizing: "border-box",
    width: "100%",
    color: "#0f172a",
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#0f172a",
    letterSpacing: "-0.03em",
    margin: "0 0 6px",
  },
  pageLead: {
    fontSize: 14,
    color: "#64748b",
    lineHeight: 1.5,
    margin: "0 0 16px",
  },
  tabBar: {
    position: "sticky",
    top: "var(--sph-h, 73px)",
    zIndex: 20,
    background: "var(--gb-color-page, #ffffff)",
    borderBottom: "1px solid #e5e7eb",
    margin: "0 -16px 8px",
    padding: "0 16px 0",
  },
  tabRail: {
    gap: 4,
    paddingBottom: 0,
  },
  tabBtn: {
    appearance: "none",
    border: "none",
    background: "transparent",
    minHeight: 44,
    padding: "10px 12px",
    fontSize: 14,
    fontWeight: 600,
    color: "#64748b",
    cursor: "pointer",
    fontFamily: "inherit",
    borderBottom: "3px solid transparent",
    borderRadius: 0,
  },
  tabBtnActive: {
    color: "#0f172a",
    fontWeight: 800,
    borderBottom: "3px solid #22C55E",
  },
  section: {
    padding: "20px 0",
    borderBottom: "1px solid #e5e7eb",
  },
  sectionLast: {
    borderBottom: "none",
  },
  sectionHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: "#0f172a",
    margin: 0,
    letterSpacing: "-0.02em",
  },
  sectionDesc: {
    fontSize: 14,
    color: "#64748b",
    margin: "0 0 12px",
    lineHeight: 1.5,
  },
  summary: {
    fontSize: 15,
    color: "#0f172a",
    margin: 0,
    lineHeight: 1.5,
    fontWeight: 600,
  },
  muted: {
    fontSize: 14,
    color: "#64748b",
    margin: 0,
    lineHeight: 1.5,
  },
  textBtn: {
    appearance: "none",
    border: "none",
    background: "transparent",
    color: "#15803d",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: "inherit",
    minHeight: 44,
    padding: "8px 4px",
    flexShrink: 0,
  },
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    padding: "0 16px",
    borderRadius: 10,
    background: "linear-gradient(180deg, #22C55E 0%, #16A34A 100%)",
    color: "#0B0F0C",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 800,
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  secondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    padding: "0 16px",
    borderRadius: 10,
    border: "1.5px solid #d1d5db",
    background: "#ffffff",
    color: "#0f172a",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    padding: "0 16px",
    borderRadius: 10,
    border: "1.5px solid #d1d5db",
    background: "#ffffff",
    color: "#334155",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  chipWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    appearance: "none",
    minHeight: 40,
    padding: "8px 14px",
    borderRadius: 999,
    border: "1.5px solid #d1d5db",
    background: "#ffffff",
    color: "#334155",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  chipSelected: {
    border: "1.5px solid #16A34A",
    background: "#16A34A",
    color: "#ffffff",
  },
  chipDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 12,
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: "#334155",
  },
  choiceRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 14,
    fontWeight: 600,
    color: "#0f172a",
    cursor: "pointer",
  },
  optText: {
    fontWeight: 500,
    color: "#94a3b8",
    fontSize: 12,
  },
  readOnly: {
    fontSize: 15,
    color: "#0f172a",
    margin: 0,
    fontWeight: 600,
  },
  input: {
    padding: "12px 14px",
    borderRadius: 10,
    border: "1.5px solid #d1d5db",
    background: "#ffffff",
    color: "#0f172a",
    fontSize: 15,
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
    boxSizing: "border-box",
    minHeight: 44,
  },
  phoneRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  inputReadonly: {
    background: "#f8fafc",
    borderColor: "#e5e7eb",
    color: "#334155",
    cursor: "default",
    flex: "1 1 180px",
  },
  statusOk: {
    fontSize: 13,
    fontWeight: 700,
    color: "#15803d",
    margin: "0 0 8px",
  },
  statusErr: {
    fontSize: 13,
    fontWeight: 700,
    color: "#b91c1c",
    margin: "0 0 8px",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "12px 0",
    borderBottom: "1px solid #f1f5f9",
    cursor: "pointer",
  },
  actionCopy: {
    minWidth: 0,
    flex: 1,
  },
  actionTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: "#0f172a",
    margin: 0,
  },
  crewBlock: {
    padding: "12px 0",
  },
  memberLine: {
    fontSize: 14,
    color: "#334155",
    margin: "6px 0 0",
    lineHeight: 1.5,
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  coinsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 8,
  },
  coinTile: {
    padding: "4px 0",
  },
  coinLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 4,
  },
  coinValue: {
    fontSize: 22,
    fontWeight: 800,
    color: "#0f172a",
  },
  mealRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 0",
    borderBottom: "1px solid #f1f5f9",
  },
  unlikeBtn: {
    appearance: "none",
    border: "none",
    background: "transparent",
    color: "#64748b",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    minHeight: 44,
    padding: "8px 4px",
    flexShrink: 0,
  },
  card: {
    maxWidth: 520,
    margin: "80px auto 0",
    padding: 28,
  },
  retryBtn: {
    marginTop: 16,
    padding: "10px 16px",
    borderRadius: 10,
    border: "none",
    background: "linear-gradient(180deg, #22C55E 0%, #16A34A 100%)",
    color: "#0B0F0C",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    minHeight: 44,
  },
};
